/**
 * NOTE: This class is auto generated by the swagger code generator program (2.4.2).
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */
package com.salaboy.snomedtest.client.swagger.api;

import com.salaboy.snomedtest.client.swagger.model.ExportConfiguration;
import io.swagger.annotations.*;
import org.springframework.http.ResponseEntity;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;

import javax.validation.Valid;

@javax.annotation.Generated(value = "io.swagger.codegen.languages.SpringCodegen", date = "2019-03-20T12:04:47.405-03:00")

@Api(value = "Export", description = "the Export API")
public interface ExportApi {

    @ApiOperation(value = "createExportJob", nickname = "createExportJobUsingPOST", notes = "", tags={ "Export", })
    @ApiResponses(value = { 
        @ApiResponse(code = 200, message = "OK"),
        @ApiResponse(code = 201, message = "Created"),
        @ApiResponse(code = 401, message = "Unauthorized"),
        @ApiResponse(code = 403, message = "Forbidden"),
        @ApiResponse(code = 404, message = "Not Found") })
    @RequestMapping(value = "/exports",
        produces = "application/json", 
        consumes = "application/json",
        method = RequestMethod.POST)
    ResponseEntity<Void> createExportJobUsingPOST(@ApiParam(value = "exportConfiguration" ,required=true )  @Valid @RequestBody ExportConfiguration exportConfiguration);


    @ApiOperation(value = "downloadRf2Archive", nickname = "downloadRf2ArchiveUsingGET", notes = "", tags={ "Export", })
    @ApiResponses(value = { 
        @ApiResponse(code = 200, message = "OK"),
        @ApiResponse(code = 401, message = "Unauthorized"),
        @ApiResponse(code = 403, message = "Forbidden"),
        @ApiResponse(code = 404, message = "Not Found") })
    @RequestMapping(value = "/exports/{exportId}/archive",
        produces = "application/zip", 
        consumes = "",
        method = RequestMethod.GET)
    ResponseEntity<Void> downloadRf2ArchiveUsingGET(@ApiParam(value = "exportId",required=true) @PathVariable("exportId") String exportId);


    @ApiOperation(value = "getExportJob", nickname = "getExportJobUsingGET", notes = "", response = ExportConfiguration.class, tags={ "Export", })
    @ApiResponses(value = { 
        @ApiResponse(code = 200, message = "OK", response = ExportConfiguration.class),
        @ApiResponse(code = 401, message = "Unauthorized"),
        @ApiResponse(code = 403, message = "Forbidden"),
        @ApiResponse(code = 404, message = "Not Found") })
    @RequestMapping(value = "/exports/{exportId}",
        produces = "application/json", 
        consumes = "",
        method = RequestMethod.GET)
    ResponseEntity<ExportConfiguration> getExportJobUsingGET(@ApiParam(value = "exportId",required=true) @PathVariable("exportId") String exportId);

}
