/**
 * NOTE: This class is auto generated by the swagger code generator program (2.4.2).
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */
package com.salaboy.snomedtest.client.swagger.api;

import com.salaboy.snomedtest.client.swagger.model.ItemsPageConceptMini;
import io.swagger.annotations.*;
import org.springframework.http.ResponseEntity;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.RequestHeader;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;
import org.springframework.web.bind.annotation.RequestParam;
import org.springframework.web.multipart.MultipartFile;

import javax.validation.Valid;
import javax.validation.constraints.*;
import java.util.List;
@javax.annotation.Generated(value = "io.swagger.codegen.languages.SpringCodegen", date = "2019-03-20T12:04:47.405-03:00")

@Api(value = "MrcmXml", description = "the MrcmXml API")
public interface MrcmXmlApi {

    @ApiOperation(value = "Retrieve valid values for the given attribute and term prefix.", nickname = "retrieveAttributeValuesUsingGET", notes = "", response = ItemsPageConceptMini.class, tags={ "MRCM XML", })
    @ApiResponses(value = { 
        @ApiResponse(code = 200, message = "OK", response = ItemsPageConceptMini.class),
        @ApiResponse(code = 401, message = "Unauthorized"),
        @ApiResponse(code = 403, message = "Forbidden"),
        @ApiResponse(code = 404, message = "Not Found") })
    @RequestMapping(value = "/mrcm/{path}/attribute-values/{attributeId}",
        produces = "application/json", 
        consumes = "",
        method = RequestMethod.GET)
    ResponseEntity<ItemsPageConceptMini> retrieveAttributeValuesUsingGET(@ApiParam(value = "path",required=true) @PathVariable("path") String path,@ApiParam(value = "attributeId",required=true) @PathVariable("attributeId") String attributeId,@NotNull @ApiParam(value = "termPrefix", required = true) @Valid @RequestParam(value = "termPrefix", required = true) String termPrefix,@ApiParam(value = "Accept-Language" ,required=true, defaultValue="en-US;q=0.8,en-GB;q=0.6") @RequestHeader(value="Accept-Language", required=true) String acceptLanguage);


    @ApiOperation(value = "Retrieve MRCM domain attributes applicable for the given parents.", nickname = "retrieveDomainAttributesUsingGET", notes = "", response = ItemsPageConceptMini.class, tags={ "MRCM XML", })
    @ApiResponses(value = { 
        @ApiResponse(code = 200, message = "OK", response = ItemsPageConceptMini.class),
        @ApiResponse(code = 401, message = "Unauthorized"),
        @ApiResponse(code = 403, message = "Forbidden"),
        @ApiResponse(code = 404, message = "Not Found") })
    @RequestMapping(value = "/mrcm/{path}/domain-attributes",
        produces = "application/json", 
        consumes = "",
        method = RequestMethod.GET)
    ResponseEntity<ItemsPageConceptMini> retrieveDomainAttributesUsingGET(@ApiParam(value = "path",required=true) @PathVariable("path") String path,@NotNull @ApiParam(value = "parentIds", required = true) @Valid @RequestParam(value = "parentIds", required = true) List<Long> parentIds,@ApiParam(value = "Accept-Language" ,required=true, defaultValue="en-US;q=0.8,en-GB;q=0.6") @RequestHeader(value="Accept-Language", required=true) String acceptLanguage);


    @ApiOperation(value = "Update system wide MRCM from XML file. This is an alternative implementation to the reference sets.", nickname = "updateMRCMFromXmlUsingPOST", notes = "", tags={ "MRCM XML", })
    @ApiResponses(value = { 
        @ApiResponse(code = 200, message = "OK"),
        @ApiResponse(code = 201, message = "Created"),
        @ApiResponse(code = 401, message = "Unauthorized"),
        @ApiResponse(code = 403, message = "Forbidden"),
        @ApiResponse(code = 404, message = "Not Found") })
    @RequestMapping(value = "/mrcm",
        produces = "application/json", 
        consumes = "multipart/form-data",
        method = RequestMethod.POST)
    ResponseEntity<Void> updateMRCMFromXmlUsingPOST(@ApiParam(value = "file detail") @RequestParam("file") MultipartFile file);

}
