/**
 * NOTE: This class is auto generated by the swagger code generator program (2.4.2).
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */
package com.salaboy.snomedtest.client.swagger.api;

import com.salaboy.snomedtest.client.swagger.model.BuildVersion;
import io.swagger.annotations.*;
import org.springframework.http.ResponseEntity;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;

@javax.annotation.Generated(value = "io.swagger.codegen.languages.SpringCodegen", date = "2019-03-20T12:04:47.405-03:00")

@Api(value = "Version", description = "the Version API")
public interface VersionApi {

    @ApiOperation(value = "Software build version and timestamp.", nickname = "getBuildInformationUsingGET", notes = "", response = BuildVersion.class, tags={ "Version", })
    @ApiResponses(value = { 
        @ApiResponse(code = 200, message = "OK", response = BuildVersion.class),
        @ApiResponse(code = 401, message = "Unauthorized"),
        @ApiResponse(code = 403, message = "Forbidden"),
        @ApiResponse(code = 404, message = "Not Found") })
    @RequestMapping(value = "/version",
        produces = "*/*", 
        consumes = "",
        method = RequestMethod.GET)
    ResponseEntity<BuildVersion> getBuildInformationUsingGET();

}
